module.exports = [
   {
        name: "Hopdoddy's Burger Bar",
        rating: 4.5,
        price: 3.5,
        location: {
            city:  "Austin" ,
            state:  "TX" ,
            streetNumber: "4615 N Lamar Blvd Suite 307" ,
            zipcode: 78757,
            },
        image:["https://imageio.forbes.com/blogs-images/garystern/files/2019/02/HopdoddySouthCongress_NickSimonite-1-1200x937.jpg?fit=bounds&format=jpg&width=960",],
        tags: ["Burgers", "American (Traditional)", "Meat Substitube"],
        foodImage: ["https://s3-media0.fl.yelpcdn.com/bphoto/isEobbaCKXB6DDIRXSu0Bg/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/wzsS37ls8pDVdipe4xJeng/o.jpg"],
    },
    {
        name: "Harvest Seasonal Kitchen",
        rating: 4.7,
        price: 2,
        location: {
            city:  "Mckinney" ,
            state:  "TX" ,
            streetNumber: "112 E Louisiana St",
            zipcode: 75069, 
            },
        image:["https://media-cdn.tripadvisor.com/media/photo-m/1280/17/22/f4/f8/dining-area.jpg"],
        tags: ["Rustic-chic, locally-sourced, American"],
        foodImage: ["https://media-cdn.tripadvisor.com/media/photo-w/0e/87/60/85/photo3jpg.jpg"," https://media-cdn.tripadvisor.com/media/photo-w/0d/d7/81/a0/braised-short-ribs.jpg"],
    },
    {
        name: "Watercourse Foods",
        rating: 4.6,
        price: 2.5,
        location: {
            city:  "Denver" ,
            state:  "CO" ,
            streetNumber: "837 E 17th Ave" ,
            zipcode: 80218,
            },
        image:["https://images.squarespace-cdn.com/content/v1/5b3ab6f65ffd206fbbaf233f/1534480960965-FWC1QHD4RFRHQMZOOM7O/DO5A5215.jpg?format=1500w"],
        tags: ["Vegan, Craft Beer, Hipster"],
        foodImage: ["https://images.squarespace-cdn.com/content/v1/5b3ab6f65ffd206fbbaf233f/1598979551717-SZ8K6HE41V0UI7RKSWSX/DO5A4658-2.jpg?format=1500w,  https://www.diningandcooking.com/wp-content/uploads/2021/06/w76tnoiqww671.jpg"],
    },
    // {
    //     name: "",
    //     rating: ,
    //     price: ,
    //     location: {
    //         city:  "" ,
    //         state:  "" ,
    //         streetNumber: "" ,
    //         zipcode: ,
    //         },
    //     image:[""],
    //     tags: [""],
    //     foodImage: [""],
    // },
    {
        name: "Bun Belly",
        rating: 4.5,
        price: 2,
        location: {
            city:  "Austin" ,
            state:  "TX" ,
            streetNumber: "5001 Airport Blvd",
            zipcode: 78751,
            },
        image:["https://www.austinchronicle.com/binary/3dfb/food_feature8-3.jpg"],
        tags: ["Asian Fusion, Vegetarian, Vietnamese"],
        foodImage: ["https://www.austinchronicle.com/binary/792b/food_feature8-4.jpg"," https://www.austinchronicle.com/binary/5e33/food_feature8-2.jpg", "https://www.austinchronicle.com/binary/fbdd/food_feature8-1.jpg"],
    },

]