module.exports = [
   {
        name: "Hopdoddy's Burger Bar",
        rating: 4.5,
        price: 3.5,
        location: {
            city:  "Austin" ,
            state:  "TX" ,
            streetNumber: "" ,
            zipcode: ,
            },
        image:["https://imageio.forbes.com/blogs-images/garystern/files/2019/02/HopdoddySouthCongress_NickSimonite-1-1200x937.jpg?fit=bounds&format=jpg&width=960",],
        tags: ["Burgers", "American (Traditional)", "Meat Substitube"],
        foodImage: ["https://s3-media0.fl.yelpcdn.com/bphoto/isEobbaCKXB6DDIRXSu0Bg/o.jpg","https://s3-media0.fl.yelpcdn.com/bphoto/wzsS37ls8pDVdipe4xJeng/o.jpg"],
    },
    {
        name: "Harvest Seasonal Kitchen",
        rating: ,
        price: ,
        location: {
            city:  "Mckinney" ,
            state:  "TX" ,
            streetNumber: "",
            zipcode: ,
            },
        image:[""],
        tags: [""],
        foodImage: [""],
    },
    {
        name: "",
        rating: ,
        price: ,
        location: {
            city:  "" ,
            state:  "" ,
            streetNumber: "" ,
            zipcode: ,
            },
        image:[""],
        tags: [""],
        foodImage: [""],
    },
    {
        name: "",
        rating: ,
        price: ,
        location: {
            city:  "" ,
            state:  "" ,
            streetNumber: "" ,
            zipcode: ,
            },
        image:[""],
        tags: [""],
        foodImage: [""],
    },
    {
        name: "Bun Belly",
        rating: 4.5,
        price: 2,
        location: {
            city:  "Austin" ,
            state:  "TX" ,
            streetNumber: "5001 Airport Blvd",
            zipcode: 78751,
            },
        image:["https://www.austinchronicle.com/binary/3dfb/food_feature8-3.jpg"],
        tags: ["Asian Fusion, Vegetarian, Vietnamese"],
        foodImage: ["https://www.austinchronicle.com/binary/792b/food_feature8-4.jpg, https://www.austinchronicle.com/binary/5e33/food_feature8-2.jpg, https://www.austinchronicle.com/binary/fbdd/food_feature8-1.jpg"],
    },

]